// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import {application} from "./application"

import TextareaAutogrow from "stimulus-textarea-autogrow"
import Notification from "stimulus-notification"
import CheckboxSelectAll from 'stimulus-checkbox-select-all'
import Clipboard from 'stimulus-clipboard'
import Carousel from 'stimulus-carousel'
import Autosave from 'stimulus-rails-autosave'
import controllers from "./**/*_controller.js"

application.register('textarea-autogrow', TextareaAutogrow)
application.register('notification', Notification)
application.register('checkbox-select-all', CheckboxSelectAll)
application.register('clipboard', Clipboard)
application.register('carousel', Carousel)
// application.register('autocomplete', Autocomplete)
application.register('autosave', Autosave)

controllers.forEach((controller) => application.register(controller.name, controller.module.default))





