version: '3.2'
services:
  barber-management-mail:
    image: 'sj26/mailcatcher'
    ports:
      - "1080:1080"
      - "1025:1025"

  barber-management-redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  barber-management-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9999:5432"
    volumes:
      - "barber-management-db-data:/var/lib/postgresql/data"

volumes:
  barber-management-db-data: