test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

supabase:
  service: S3
  access_key_id: <%= ENV.fetch('SUPABASE_STORAGE_ACCESS_KEY', '') %>
  secret_access_key: <%= ENV.fetch('SUPABASE_STORAGE_SECRET_KEY', '') %>
  region: <%= ENV.fetch('SUPABASE_STORAGE_REGION', 'us-east-1') %>
  bucket: <%= ENV.fetch('SUPABASE_STORAGE_BUCKET', 'orbi') %>
  endpoint: <%= ENV.fetch('SUPABASE_STORAGE_ENDPOINT', '') %>
  force_path_style: true
