class FixReceiptTemplates < ActiveRecord::Migration[7.0]
  def change
    ReceiptTemplate.where('updated_at < ?', 4.hours.ago).find_each do |receipt_template|

      if receipt_template.name == 'Recebimento Padrão'
        receipt_template.content = '<h2 class="min-h-[1rem] print:leading-6 print:scale-[1.7] print:mx-44 print:font-sans" style="text-align: center">Recibo</h2><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans">Eu, [MINHA_EMPRESA], CPF/CNPJ: [MINHA_EMPRESA_DOCUMENTO], declaro que recebi de [NOME_CLIENTE], inscrita no CPF/CNPJ: [DOCUMENTO_CLIENTE], a importância supra de [VALOR_ITEM], referente a [DESCRICAO_ITEM]. E para clareza, afirmo o presente.</p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans">[MINHA_EMPRESA_CIDADE]/[MINHA_EMPRESA_ESTADO],</p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans">[DATA_ATUAL].</p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans" style="text-align: center">&nbsp;____________________________________________________________________<br>Nome: [MINHA_EMPRESA], CPF/CNPJ: [MINHA_EMPRESA_DOCUMENTO]&nbsp;&nbsp;</p>'
      end

      if receipt_template.name == 'Despesa Padrão'
        receipt_template.content = '<h2 class="min-h-[1rem] print:leading-6 print:scale-[1.7] print:mx-44 print:font-sans" style="text-align: center">Recibo</h2><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans">Eu, [NOME_CLIENTE], CPF/CNPJ: [DOCUMENTO_CLIENTE], declaro que recebi de [MINHA_EMPRESA], inscrita no CPF/CNPJ: [MINHA_EMPRESA_DOCUMENTO], a importância supra de [VALOR_ITEM], referente a [DESCRICAO_ITEM]. E para clareza, afirmo o presente.</p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans">[MINHA_EMPRESA_CIDADE]/[MINHA_EMPRESA_ESTADO],</p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans">[DATA_ATUAL].</p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans"></p><p class="min-h-[1rem] text-xs print:min-h-[2rem] print:leading-6 print:text-xl print:font-sans" style="text-align: center">&nbsp;____________________________________________________________________<br>Nome: [MINHA_EMPRESA], CPF/CNPJ: [MINHA_EMPRESA_DOCUMENTO]&nbsp;&nbsp;</p>'
      end
      receipt_template.save
    end
  end
end

